version: '3.8'

services:
  link-shortener:
    build: ./
    command: ["./wait-for-postgres.sh", "postgres_db", "./link-shortener"]
    ports:
      - 8033:8033
    depends_on:
      - postgres_db
      - nginx
    environment:
      - CONFIG_PATH=./config
      - CONFIG_NAME=local
      - POSTGRES_PASSWORD=12345

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"
  
  postgres_db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=linkShortenerDB
    volumes:
      - storage-data:/pgdata
    ports:
      - 5436:5432
      

volumes:
  storage-data: